export const experiments = [
  {
    url: '/1-gsap-basics',
    num: '01',
    name: 'GSAP Basics',
    desc: 'Character-by-character reveal with SplitText staggered tweens',
    tech: 'SplitText · gsap.from()',
    accent: '#4fb8b2',
  },
  {
    url: '/2-css-version',
    num: '02',
    name: 'CSS Version',
    desc: 'The same entrance animation rebuilt in pure CSS with custom properties',
    tech: 'CSS @keyframes · custom props',
    accent: '#8b9cf4',
  },
  {
    url: '/3-timelines',
    num: '03',
    name: 'Timelines',
    desc: 'Orchestrate complex multi-phase sequences with GSDevTools scrubbing',
    tech: 'gsap.timeline() · GSDevTools',
    accent: '#f4a460',
  },
  {
    url: '/4-scroll-trigger',
    num: '04',
    name: 'Scroll Trigger',
    desc: 'SVG paths draw themselves as you scroll — toggle on enter and exit',
    tech: 'ScrollTrigger · DrawSVG',
    accent: '#5cb85c',
  },
  {
    url: '/5-follow-scroll',
    num: '05',
    name: 'Follow Scroll',
    desc: 'Pin an SVG logo while its outline fills in lock-step with scroll progress',
    tech: 'pin · scrub · DrawSVG',
    accent: '#e8a0bf',
  },
  {
    url: '/6-variables',
    num: '06',
    name: 'CSS Variables',
    desc: 'Font weight and letter-spacing warp live with cursor distance',
    tech: 'mousemove · CSS custom props',
    accent: '#f7c59f',
  },
  {
    url: '/7-custom-cursor',
    num: '07',
    name: 'Custom Cursor',
    desc: 'A soft blob trails your pointer with silky GSAP lerp interpolation',
    tech: 'GSAP ticker · lerp',
    accent: '#c9a8e0',
  },
  {
    url: '/8-image-sequence',
    num: '08',
    name: 'Image Sequence',
    desc: '300 frames rendered to Canvas in perfect sync with scroll position',
    tech: 'Canvas 2D · ScrollTrigger scrub',
    accent: '#60d7cf',
  },
  {
    url: '/9-reduced-motion',
    num: '09',
    name: 'Reduced Motion',
    desc: 'The same sequence, rebuilt with accessibility as a first-class concern',
    tech: 'prefers-reduced-motion',
    accent: '#a8d8a8',
  },
  {
    url: '/10-device-profiling',
    num: '10',
    name: 'Device Profiling',
    desc: 'GPU tier and battery level gate a WebGL fluid shader at runtime',
    tech: 'detect-gpu · WebGL shaders',
    accent: '#ff9a3c',
  },
  {
    url: '/11-animating-3d-scenes',
    num: '11',
    name: '3D Scenes',
    desc: 'GSAP drives position, rotation, and light intensity on a Three.js scene',
    tech: 'React Three Fiber · GSAP',
    accent: '#4db8b8',
  },
]

export const techPills = [
  { label: 'SplitText', x: '8%', y: '22%' },
  { label: 'ScrollTrigger', x: '78%', y: '18%' },
  { label: 'DrawSVG', x: '85%', y: '68%' },
  { label: 'Three.js', x: '6%', y: '72%' },
  { label: 'React Three Fiber', x: '72%', y: '82%' },
  { label: 'GSAP Ticker', x: '14%', y: '48%' },
  { label: 'Canvas 2D', x: '82%', y: '44%' },
]

export const marqueeItems = [
  '01 GSAP Basics',
  '02 CSS Animation',
  '03 Timelines',
  '04 ScrollTrigger',
  '05 Follow Scroll',
  '06 CSS Variables',
  '07 Custom Cursor',
  '08 Image Sequence',
  '09 Reduced Motion',
  '10 Device Profiling',
  '11 Animating 3D',
]

export const resources = [
  { label: 'Easing Reference', url: 'https://easings.net/' },
  { label: 'GSAP Docs v3', url: 'https://gsap.com/docs/v3/' },
  { label: 'React Scan', url: 'https://react-scan.com/' },
  { label: 'react-device-detect', url: 'https://www.npmjs.com/package/react-device-detect' },
  { label: 'detect-gpu', url: 'https://www.npmjs.com/package/detect-gpu' },
  { label: 'Leva', url: 'https://github.com/pmndrs/leva' },
  { label: 'Zustand', url: 'https://www.npmjs.com/package/zustand' },
  { label: 'Lenis (smooth scroll)', url: 'https://www.npmjs.com/package/lenis' },
  { label: 'Tailwind CSS', url: 'https://tailwindcss.com/' },
]
